eureka:
  client:
    service-url:
      default-zone: http://aaaaaa/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}


logging:
  level:
    org.springframework.web: info

say:
  cheese: kimchi!!