server:
  port: 8081

zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
  routes:
    account-service:
      path: /accounts/**
      service-id: account-service
      strip-prefix: true
  ignored-services: '*'  #route에 정의되지 않은 요청을 무시함.
  sensitive-headers: '*' #header by-pass

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      default-zone: http://aaaaaa/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org.springframework.web: info
